{
 "title": "2023_0412_Discussed_Panel",
 "description": "Visualize all MicroProfile Metrics for WildFly 26+",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "ns",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ActiveMq Artemis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Address Paging",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "artemis_number_of_pages{namespace=~\"$ns\"}"
      }
     ]
    },
    {
     "title": "Disk Storage Usege",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "artemis_disk_store_usage{namespace=~\"$ns\"  }",
       "legendFormat": "{{ pod}}"
      }
     ]
    },
    {
     "title": "Connections and Consumers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "artemis_connection_count{namespace=~\"$ns\"   }",
       "legendFormat": "Connection Count"
      },
      {
       "expr": "artemis_consumer_count{namespace=~\"$ns\"  }",
       "legendFormat": "{{ address }}"
      }
     ]
    },
    {
     "title": "ActiveMQ Artemis JVM Committed  Memory Usage",
     "type": "graph",
     "description": "The amount of memory in bytes that is committed for the Java virtual machine to use",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{namespace=~\"$ns\" }",
       "legendFormat": " {{ id }} - {{ area }} "
      }
     ]
    },
    {
     "title": "ActiveMQ Artemis JVM Memory Usage",
     "type": "graph",
     "description": "The amount of memory in bytes for the Java virtual machine to use",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=~\"$ns\"}",
       "legendFormat": "{{id}}-{{ area }}"
      }
     ]
    }
   ]
  },
  {
   "title": "MicroProfile Base Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU Load",
     "type": "graph",
     "description": "Displays the \"recent cpu usage\" for the Java Virtual Machine process.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "base_cpu_processCpuLoad{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "JVM Uptime",
     "type": "stat",
     "description": "Displays the uptime of the Java virtual machine",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "format": "s",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "base_jvm_uptime_seconds{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "Available Processors",
     "type": "stat",
     "description": "Displays the number of processors available to the Java virtual machine. This value may change during a particular invocation of the virtual machine.",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
     "format": "short",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "base_cpu_availableProcessors{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "Current Thread count",
     "type": "stat",
     "description": "Number of currently deployed threads",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
     "format": "short",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "base_thread_count{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "Peak Thread Count",
     "type": "stat",
     "description": "Displays the peak live thread count since the Java virtual machine started or peak was reset. This includes daemon and non-daemon threads.",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
     "format": "short",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "base_thread_max_count{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "System Load Average",
     "type": "stat",
     "description": "Displays the system load average for the last minute. The system load average is the sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time. The way in which the load average is calculated is operating system specific but is typically a damped time-dependent average. If the load average is not available, a negative value is displayed. This attribute is designed to provide a hint about the system load and may be queried frequently. The load average may be unavailable on some platform where it is expensive to implement this method.",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "base_cpu_systemLoadAverage{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "Current Loaded Class Count",
     "type": "stat",
     "description": "Displays the number of classes that are currently loaded in the Java virtual machine.",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
     "format": "short",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "base_classloader_loadedClasses_count{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "Daemon Thread Count",
     "type": "stat",
     "description": "Displays the current number of live daemon threads.",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
     "format": "short",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "base_thread_daemon_count{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "Heap Memory",
     "type": "graph",
     "description": "Displays the amount of used memory and max memory.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "base_memory_usedHeap_bytes{namespace=~\"$ns\" }",
       "legendFormat": "{{ __name__ }}/{{ instance }}"
      },
      {
       "expr": "base_memory_maxHeap_bytes{namespace=~\"$ns\" }",
       "legendFormat": "{{ __name__ }}/{{ instance }}"
      },
      {
       "expr": "base_memory_committedHeap_bytes{namespace=~\"$ns\" }",
       "legendFormat": "{{ __name__ }}/{{ instance }}"
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "graph",
     "description": "Displays the total number of collections that have occurred. This attribute lists -1 if the collection count is undefined for this collector.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "base_gc_total{namespace=~\"$ns\" }",
       "legendFormat": "{{name}}/{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "Total Unloaded Class Count",
     "type": "graph",
     "description": "Displays the total number of classes unloaded since the Java virtual machine has started execution.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "base_classloader_unloadedClasses_total{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "GC Time",
     "type": "graph",
     "description": "Displays the approximate accumulated collection elapsed time in milliseconds. This attribute displays -1 if the collection elapsed time is undefined for this collector. The Java virtual machine implementation may use a high resolution timer to measure the elapsed time. This attribute may display the same value even if the collection count has been incremented if the collection elapsed time is very short.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(base_gc_time_total_seconds{namespace=~\"$ns\" }[1m])",
       "legendFormat": "{{ name  }}/{{ instance }}/{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "Total Loaded Class Count",
     "type": "graph",
     "description": "Displays the total number of classes that have been loaded since the Java virtual machine has started execution.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "base_classloader_loadedClasses_total{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "Non Heap Memory",
     "type": "graph",
     "description": "Displays the amount of used memory and max memory.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "base_memory_usedNonHeap_bytes{namespace=~\"$ns\" }",
       "legendFormat": "{{ __name__ }}/{{instance}}"
      },
      {
       "expr": "base_memory_maxNonHeap_bytes{namespace=~\"$ns\" }",
       "legendFormat": "{{ __name__ }}/{{instance}}"
      },
      {
       "expr": "base_memory_committedNonHeap_bytes{namespace=~\"$ns\" }",
       "legendFormat": "a{{ __name__ }}/{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MicroProfile WildFly BufferPool and MemoryPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "BufferPool used memory direct and mapped",
     "type": "graph",
     "description": "The memory used by the NIO pool: direct and mapped",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "vendor_BufferPool_used_memory_direct_bytes{namespace=~\"$ns\" }",
       "legendFormat": "{{__name__}}/{{instance}} "
      },
      {
       "expr": "vendor_BufferPool_used_memory_mapped_bytes{namespace=~\"$ns\" }",
       "legendFormat": "{{__name__}}/{{instance}} "
      }
     ]
    },
    {
     "title": "memoryPool.CodeHeap 'non-profiled nmethods'",
     "type": "graph",
     "description": "Max and current usage of the CodeHeap 'non-profiled nmethods' memory pool",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "vendor_memoryPool_Code_Cache_usage_bytes{namespace=~\"$ns\" }",
       "legendFormat": "{{__name__}}/{{instance}} "
      },
      {
       "expr": "vendor_memoryPool_Code_Cache_usage_max_bytes{namespace=~\"$ns\" }",
       "legendFormat": "{{__name__}}/{{instance}} "
      }
     ]
    },
    {
     "title": "memoryPool.Compressed Class Space",
     "type": "graph",
     "description": "Max and current usage  of the Compressed Class Space memory pool",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "vendor_memoryPool_Compressed_Class_Space_usage_bytes{namespace=~\"$ns\" }",
       "legendFormat": "{{__name__}}/{{instance}} "
      },
      {
       "expr": "vendor_memoryPool_Compressed_Class_Space_usage_max_bytes{namespace=~\"$ns\" }",
       "legendFormat": "{{__name__}}/{{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "MicroProfile WildFly DataSources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "wildfly_datasources_pool_active_count",
   "type": "stat",
   "description": "The active count",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_active_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_jdbc_prepared_statement_cache_current_size",
   "type": "stat",
   "description": "The number of prepared and callable statements currently cached in the statement cache",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_jdbc_prepared_statement_cache_current_size{namespace=~\"$ns\"}",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_jdbc_prepared_statement_cache_miss_count",
   "type": "stat",
   "description": "The number of times that a statement request could not be satisfied with a statement from the cache",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_jdbc_prepared_statement_cache_miss_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_jdbc_prepared_statement_cache_delete_count",
   "type": "stat",
   "description": "The number of statements discarded from the cache",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_jdbc_prepared_statement_cache_delete_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_created_count",
   "type": "stat",
   "description": "The created count",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_created_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_wait_count",
   "type": "stat",
   "description": "The number of requests that had to wait to obtain a physical connection",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_wait_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_idle_count",
   "type": "stat",
   "description": "The number of physical connections currently idle",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_idle_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_destroyed_count",
   "type": "stat",
   "description": "The destroyed count",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_destroyed_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_total_usage_time",
   "type": "stat",
   "description": "The total time spent using physical connections",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_total_usage_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_in_use_count",
   "type": "stat",
   "description": "The number of physical connections currently in use",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_in_use_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_jdbc_prepared_statement_cache_hit_count",
   "type": "stat",
   "description": "The number of times that statements from the cache were used",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_jdbc_prepared_statement_cache_hit_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_max_get_time",
   "type": "stat",
   "description": "The maximum time for obtaining a physical connection",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_max_get_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xaforget_max_time",
   "type": "stat",
   "description": "The maximum time for a XAResource forget invocation",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xaforget_max_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_average_pool_time",
   "type": "stat",
   "description": "The average time for a physical connection spent in the pool",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_average_pool_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_available_count",
   "type": "stat",
   "description": "The available count",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_available_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_max_wait_count",
   "type": "stat",
   "description": "The maximum number of threads waiting for a connection",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_max_wait_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xastart_max_time",
   "type": "stat",
   "description": "The maximum time for a XAResource start invocation",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xastart_max_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_max_creation_time",
   "type": "stat",
   "description": "The maximum time for creating a physical connection",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_max_creation_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_average_get_time",
   "type": "stat",
   "description": "The average time spent obtaining a physical connection",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_average_get_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_total_blocking_time",
   "type": "stat",
   "description": "The total blocking time",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 28 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_total_blocking_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xaend_total_time",
   "type": "stat",
   "description": "The total time for all XAResource end invocations",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xaend_total_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xacommit_max_time",
   "type": "stat",
   "description": "The maximum time for a XAResource commit invocation",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xacommit_max_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_max_used_count",
   "type": "stat",
   "description": "The maximum number of connections used",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_max_used_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xaend_max_time",
   "type": "stat",
   "description": "The maximum time for a XAResource end invocation",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xaend_max_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xarecover_total_time",
   "type": "stat",
   "description": "The total time for all XAResource recover invocations",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xarecover_total_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xaprepare_max_time",
   "type": "stat",
   "description": "The maximum time for a XAResource prepare invocation",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xaprepare_max_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_total_creation_time",
   "type": "stat",
   "description": "The total time spent creating physical connections",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_total_creation_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xarollback_max_time",
   "type": "stat",
   "description": "The maximum time for a XAResource rollback invocation",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 40 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xarollback_max_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_max_wait_time",
   "type": "stat",
   "description": "The maximum wait time for a connection",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 46 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_max_wait_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xaforget_total_time",
   "type": "stat",
   "description": "The total time for all XAResource forget invocations",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 46 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xaforget_total_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xarecover_max_time",
   "type": "stat",
   "description": "The maximum time for a XAResource recover invocation",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 46 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xarecover_max_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_average_blocking_time",
   "type": "stat",
   "description": "Average Blocking Time for pool",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 46 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_average_blocking_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xacommit_average_time",
   "type": "stat",
   "description": "The average time for a XAResource commit invocation",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 52 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xacommit_average_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xarollback_total_time",
   "type": "stat",
   "description": "The total time for all XAResource rollback invocations",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 52 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xarollback_total_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xacommit_total_time",
   "type": "stat",
   "description": "The total time for all XAResource commit invocations",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 52 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xacommit_total_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xaprepare_total_time",
   "type": "stat",
   "description": "The total time for all XAResource prepare invocations",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 52 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xaprepare_total_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xaprepare_average_time",
   "type": "stat",
   "description": "The average time for a XAResource prepare invocation",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 58 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xaprepare_average_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xastart_total_time",
   "type": "stat",
   "description": "The total time for all XAResource start invocations",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 58 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xastart_total_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_average_usage_time",
   "type": "stat",
   "description": "The average time spent using a physical connection",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 58 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_average_usage_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_max_pool_time",
   "type": "stat",
   "description": "The maximum time for a physical connection in the pool",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 58 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_max_pool_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_timed_out",
   "type": "stat",
   "description": "The timed out count",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 64 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_timed_out{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xaend_average_time",
   "type": "stat",
   "description": "The average time for a XAResource end invocation",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 64 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xaend_average_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_total_get_time",
   "type": "stat",
   "description": "The total time spent obtaining physical connections",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 64 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_total_get_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_average_creation_time",
   "type": "stat",
   "description": "The average time spent creating a physical connection",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 64 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_average_creation_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xaend_count",
   "type": "stat",
   "description": "The number of XAResource end invocations",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 70 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xaend_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xarollback_average_time",
   "type": "stat",
   "description": "The average time for a XAResource rollback invocation",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 70 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xarollback_average_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xaforget_average_time",
   "type": "stat",
   "description": "The average time for a XAResource forget invocation",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 70 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xaforget_average_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xarecover_average_time",
   "type": "stat",
   "description": "The average time for a XAResource recover invocation",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 70 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xarecover_average_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xarollback_count",
   "type": "stat",
   "description": "The number of XAResource rollback invocations",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 76 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xarollback_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_max_usage_time",
   "type": "stat",
   "description": "The maximum time using a physical connection",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 76 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_max_usage_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xastart_average_time",
   "type": "stat",
   "description": "The average time for a XAResource start invocation",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 76 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xastart_average_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_blocking_failure_count",
   "type": "stat",
   "description": "The number of failures trying to obtain a physical connection",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 76 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_blocking_failure_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xastart_count",
   "type": "stat",
   "description": "The number of XAResource start invocations",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 82 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xastart_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xaforget_count",
   "type": "stat",
   "description": "The number of XAResource forget invocations",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 82 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xaforget_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_total_pool_time",
   "type": "stat",
   "description": "The total time spent by physical connections in the pool",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 82 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_total_pool_time{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xacommit_count",
   "type": "stat",
   "description": "The number of XAResource commit invocations",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 82 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xacommit_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xaprepare_count",
   "type": "stat",
   "description": "The number of XAResource prepare invocations",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 88 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xaprepare_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "wildfly_datasources_pool_xarecover_count",
   "type": "stat",
   "description": "The number of XAResource recover invocations",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 88 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_xarecover_count{namespace=~\"$ns\" }",
     "legendFormat": "{{job}}/{{instance}} data_source={{data_source}}"
    }
   ]
  },
  {
   "title": "MicroProfile WildFly Undertow Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "collapsed": true,
   "panels": [
    {
     "title": "wildfly_undertow_active_sessions",
     "type": "stat",
     "description": "Number of active sessions",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
     "format": "short",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "wildfly_undertow_active_sessions{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} deployment={{deployment}}/subdeployment={{subdeployment}}"
      }
     ]
    },
    {
     "title": "wildfly_transactions_number_of_inflight_transactions",
     "type": "stat",
     "description": "The number of transactions that have begun but not yet terminated.",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
     "format": "short",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "wildfly_transactions_number_of_inflight_transactions{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "wildfly_request_controller_active_requests",
     "type": "stat",
     "description": "The number of requests that are currently running in the server",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
     "format": "short",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "wildfly_request_controller_active_requests{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "wildfly_undertow_sessions_created",
     "type": "graph",
     "description": "Total sessions created",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wildfly_undertow_sessions_created_total{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} deployment={{deployment}}/subdeployment={{subdeployment}}"
      }
     ]
    },
    {
     "title": "wildfly_undertow_highest_session_count",
     "type": "stat",
     "description": "The maximum number of sessions that have been active simultaneously",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
     "format": "short",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "wildfly_undertow_highest_session_count{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} deployment={{deployment}}/subdeployment={{subdeployment}}"
      }
     ]
    },
    {
     "title": "wildfly_undertow_session_avg_alive_time",
     "type": "stat",
     "description": "Average time that expired sessions had been alive",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 8 },
     "format": "s",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "wildfly_undertow_session_avg_alive_time_seconds{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} deployment={{deployment}}/subdeployment={{subdeployment}}"
      }
     ]
    },
    {
     "title": "wildfly_undertow_session_max_alive_time",
     "type": "stat",
     "description": "The longest time that an expired session had been alive",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 8 },
     "format": "s",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "wildfly_undertow_session_max_alive_time_seconds{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} deployment={{deployment}}/subdeployment={{subdeployment}}"
      }
     ]
    },
    {
     "title": "wildfly_transactions_number_of_aborted_transactions",
     "type": "graph",
     "description": "The number of aborted (i.e. rolledback) transactions.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wildfly_transactions_number_of_aborted_transactions_total{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "wildfly_transactions_number_of_nested_transactions",
     "type": "graph",
     "description": "The total number of nested (sub) transactions created.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wildfly_transactions_number_of_nested_transactions_total{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "wildfly_undertow_rejected_sessions",
     "type": "graph",
     "description": "Number of rejected sessions",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wildfly_undertow_rejected_sessions_total{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} deployment={{deployment}}/subdeployment={{subdeployment}}"
      }
     ]
    },
    {
     "title": "wildfly_undertow_expired_sessions",
     "type": "graph",
     "description": "Number of sessions that have expired",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wildfly_undertow_expired_sessions_total{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} deployment={{deployment}}/subdeployment={{subdeployment}}"
      }
     ]
    },
    {
     "title": "wildfly_transactions_number_of_timed_out_transactions",
     "type": "graph",
     "description": "The number of transactions that have rolled back due to timeout.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wildfly_transactions_number_of_timed_out_transactions_total{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "wildfly_transactions_number_of_application_rollbacks",
     "type": "graph",
     "description": "The number of transactions that have been rolled back by application request. This includes those that timeout, since the timeout behavior is considered an attribute of the application configuration.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wildfly_transactions_number_of_application_rollbacks_total{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "wildfly_transactions_number_of_heuristics",
     "type": "graph",
     "description": "The number of transactions which have terminated with heuristic outcomes.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {}
     ]
    },
    {
     "title": "wildfly_undertow_max_active_sessions",
     "type": "stat",
     "description": "The maximum allowed number of concurrent sessions that this session manager supports",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
     "format": "short",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "wildfly_undertow_max_active_sessions{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} deployment={{deployment}}/subdeployment={{subdeployment}}"
      }
     ]
    },
    {
     "title": "wildfly_undertow_bytes_sent",
     "type": "graph",
     "description": "The number of bytes that have been sent out on this listener",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "wildfly_undertow_bytes_sent_bytes{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} ajp_listener={{ajp_listener}}/http_listener={{http_listener}}/https_listener={{https_listener}}/server={{server}}"
      }
     ]
    },
    {
     "title": "wildfly_transactions_number_of_transactions",
     "type": "graph",
     "description": "The total number of transactions (top-level and nested) created",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wildfly_transactions_number_of_transactions_total{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "wildfly_transactions_number_of_resource_rollbacks",
     "type": "graph",
     "description": "The number of transactions that rolled back due to resource (participant) failure.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wildfly_transactions_number_of_resource_rollbacks_total{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "wildfly_transactions_number_of_system_rollbacks",
     "type": "graph",
     "description": "The number of transactions that have been rolled back due to internal system errors.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wildfly_transactions_number_of_system_rollbacks_total{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "wildfly_undertow_processing_time",
     "type": "graph",
     "description": "The total processing time of all requests handed by this listener",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wildfly_undertow_processing_time_total_seconds{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} ajp_listener={{ajp_listener}}/http_listener={{http_listener}}/https_listener={{https_listener}}/server={{server}}"
      }
     ]
    },
    {
     "title": "wildfly_undertow_error_count",
     "type": "graph",
     "description": "The number of 500 responses that have been sent by this listener",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wildfly_undertow_",
       "legendFormat": "{{job}}/{{instance}} ajp_listener={{ajp_listener}}/http_listener={{http_listener}}/https_listener={{https_listener}}/server={{server}}"
      }
     ]
    },
    {
     "title": "wildfly_transactions_number_of_committed_transactions",
     "type": "graph",
     "description": "The number of committed transactions.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wildfly_transactions_number_of_committed_transactions_total{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} "
      }
     ]
    },
    {
     "title": "wildfly_undertow_bytes_received",
     "type": "graph",
     "description": "The number of bytes that have been received by this listener",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "wildfly_undertow_bytes_received_bytes{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} ajp_listener={{ajp_listener}}/http_listener={{http_listener}}/https_listener={{https_listener}}/server={{server}}"
      }
     ]
    },
    {
     "title": "wildfly_undertow_max_request_time",
     "type": "stat",
     "description": "Maximal time for processing request",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
     "format": "s",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "wildfly_undertow_max_request_time_seconds{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} deployment={{deployment}}/servlet={{servlet}}/subdeployment={{subdeployment}}"
      }
     ]
    },
    {
     "title": "wildfly_undertow_max_processing_time",
     "type": "stat",
     "description": "The maximum processing time taken by a request on this listener",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 35 },
     "format": "s",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "wildfly_undertow_max_processing_time_seconds{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} ajp_listener={{ajp_listener}}/http_listener={{http_listener}}/https_listener={{https_listener}}/server={{server}}"
      }
     ]
    },
    {
     "title": "wildfly_undertow_min_request_time",
     "type": "stat",
     "description": "Minimal time for processing request",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 35 },
     "format": "s",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "wildfly_undertow_min_request_time_seconds{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} deployment={{deployment}}/servlet={{servlet}}/subdeployment={{subdeployment}}"
      }
     ]
    },
    {
     "title": "wildfly_undertow_request_count",
     "type": "graph",
     "description": "Number of all requests",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wildfly_undertow_request_count_total{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} ajp_listener={{ajp_listener}}/deployment={{deployment}}/http_listener={{http_listener}}/https_listener={{https_listener}}/server={{server}}/servlet={{servlet}}/subdeployment={{subdeployment}}"
      }
     ]
    },
    {
     "title": "wildfly_undertow_total_request_time",
     "type": "graph",
     "description": "Total time spend in processing all requests",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wildfly_undertow_total_request_time_total_seconds{namespace=~\"$ns\" }",
       "legendFormat": "{{job}}/{{instance}} deployment={{deployment}}/servlet={{servlet}}/subdeployment={{subdeployment}}"
      }
     ]
    }
   ]
  }
 ]
}