{
 "title": "Apache ActiveMq Artemis v2023",
 "description": "Dashboard for monitoring Apache Activemq Artemis",
 "tags": [ "apache artemis" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values(artemis_connection_count{namespace=\"$ns\",jobservice=\"$svc\"}, instance)"
    }
   },
   { "name": "PROMETHEUS_DS", "label": "Source", "query": "prometheus" },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {
     "query": "label_values(artemis_connection_count, namespace)"
    }
   },
   {
    "name": "svc",
    "label": "service",
    "query": {
     "query": "label_values(artemis_connection_count{namespace=\"$ns\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Storage Usege",
   "type": "stat",
   "description": "HELP artemis_disk_store_usage Fraction of total disk store used",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "artemis_disk_store_usage{namespace=\"$ns\" }",
     "legendFormat": "{{ broker}} - {{$ns}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_start_time{namespace=\"$ns\" }",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Started",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_start_time{namespace=\"$ns\" ,pod=\"ex-aao-ss-0\" }/60/60/100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Free File Descriptors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_max_fds{namespace=\"$ns\",service=\"$svc\"} - process_open_fds{namespace=\"$ns\",service=\"$svc\"}"
    }
   ]
  },
  {
   "title": "Journal Buffer Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "artemis_journal_buffer_size{instance=\"$instance\", job=\"broker\"}"
    },
    {}
   ]
  },
  {
   "title": "Address Paging",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "artemis_number_of_pages{namespace=\"$ns\",service=\"$svc\"}"
    }
   ]
  },
  {
   "title": "Journal Buffer Timeout",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "artemis_journal_buffer_timeout{instance=\"$instance\", job=\"broker\"}"
    },
    {}
   ]
  },
  {
   "title": "Journal Max I/O",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "artemis_journal_max_io{instance=\"$instance\", job=\"broker\"}"
    },
    {}
   ]
  },
  {
   "title": "Message Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "artemis_message_count", "legendFormat": "{{ address }}" }
   ]
  },
  {
   "title": "Disk Storage Usege",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "artemis_disk_store_usage{namespace=\"$ns\" ,broker=\"amq-broker\" }",
     "legendFormat": "{{ pod}}"
    }
   ]
  },
  {
   "title": "Connections and Consumers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "artemis_connection_count{namespace=\"$ns\" ,service=\"$svc\" }",
     "legendFormat": "Connection Count"
    },
    {
     "expr": "artemis_consumer_count{namespace=\"$ns\" ,service=\"$svc\" }",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "Artemis Address Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "artemis_address_size{namespace=\"$namespace\" }",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "JVM Committed  Memory Usage",
   "type": "graph",
   "description": "The amount of memory in bytes that is committed for the Java virtual machine to use",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{namespace=\"$ns\",service=\"$svc\"}",
     "legendFormat": " {{ id }} - {{ area }} "
    }
   ]
  },
  {
   "title": "JVM Memory Pool Usage",
   "type": "timeseries",
   "description": "An estimate of the memory that the Java virtual machine is using for this buffer pool",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{namespace=\"$ns\",service=\"$svc\"}",
     "legendFormat": "{{ id}} / {{ job }}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "description": "The amount of memory in bytes for the Java virtual machine to use",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=\"$ns\",service=\"$svc\"}",
     "legendFormat": "{{id}}-{{ area }}"
    }
   ]
  },
  {
   "title": "JMV Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"$instance\",job=\"broker\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "jvm_threads_peak{instance=\"$instance\",job=\"broker\"}",
     "legendFormat": "Peak"
    }
   ]
  }
 ]
}