apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: database
  labels:
    application: postgresql-database
spec:
  replicas: 1
  selector:
    matchLabels:
      application: postgresql-database
  template:
    metadata:
      labels:
        application: postgresql-database
    spec:
      containers:
      - name: postgresql-database
        image: postgres:latest
        env: 
        - name: POSTGRES_USER
          value: "todos"
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-database-service
  namespace: database
spec:
  selector:
    application: postgresql-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
