apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly-app-deployment
  namespace: wildfly-ex-app
  # labels:
  #   application: wildfly-ex-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: example-app
      application: wildfly-ex-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-app
        application: wildfly-ex-app
      annotations:
        prometheus.io/port: '8080'
        prometheus.io/scheme: http
        prometheus.io/scrape: 'true'  
    spec:
      containers:
      - name: wildfly-ex-app
        image: wildfly-todo-backend:latest
        imagePullPolicy: IfNotPresent
        env: 
        - name: POSTGRESQL_SERVICE_HOST
          value: "postgresql-database-service.database.svc.cluster.local"
        - name: POSTGRESQL_SERVICE_PORT
          value: "5432"
        - name: POSTGRESQL_USER
          value: "todos"
        - name: POSTGRESQL_PASSWORD
          value: "mysecretpassword"
        - name: POSTGRESQL_DATASOURCE
          value: "ToDos"
        - name: JAVA_OPTS
          value:   >-
                  -Dwildfly.statistics-enabled=true
        - name: TZ
          value: 'Asia/Taipei'          
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 9990
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: wildfly-app-service
  namespace: wildfly-ex-app
  labels:
    tier: frontend
spec:
  selector:
    app.kubernetes.io/name: example-app
  ports:
    - name: wildfly-ex-app
      protocol: TCP
      port: 8080
      targetPort: web
    - name: wildfly-ex-m
      protocol: TCP
      port: 9990
      targetPort: metrics
